<?php
/**
 * @file subtheme.inc
 */
/**
 * (Re-)Write style sheet(s).
 *
 * Stylesheets are organized like this:
 *    files/subtheme/subtheme_name/subtheme_name.css
 *    files/subtheme/subtheme_name/images/imageA.png
 *    files/subtheme/subtheme_name/images/imageB.jpg
 *    files/subtheme/subtheme_name/images/imageC.gif
 * 
 * @param $subtheme
 *  object, $subtheme 
 */
function subtheme_css($subtheme) {
//  $css = subtheme_generate_css($selector);   
//  $written = subtheme_write_css($css);
  if (!$written) {
    // TODO handle error here. Notify user.  
  }
}


